version: "3.9"
   
services:
  fairness_web:
    container_name: fair_web
    image: ${BACKEND_IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: ./fairness_web
      dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ${RESOURCE_PATH}:${DATA_DIR}
    environment: 
      - DATA_PATH=${DATA_DIR}
      - DB_FILE_NAME=${DB_FILE_NAME}
      - MAPPING_FILE_NAME=${MAPPING_FILE_NAME}
  # fairness_front:
  #   container_name: fair_front
  #   image: ${FRONTEND_IMAGE_NAME}:${IMAGE_TAG}
  #   build:
  #     context: ./fairness_front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${FRONTEND_PORT}:80"
  #   depends_on: 
  #     - fairness_web